export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const OFFERS_LIST_REQUEST = 'OFFERS_LIST_REQUEST';
export const OFFERS_LIST_SUCCESS = 'OFFERS_LIST_SUCCESS';
export const OFFERS_LIST_FAIL = 'OFFERS_LIST_FAIL';
